name: Delete 
on: 
  workflow_dispatch:   
jobs:
  clean:
    name: delete
    runs-on: ubuntu-latest
    steps:
      - name: delete Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
             cd /pub/ypopovic/
             rm -rf cmsc389T-web-template/
